title = 'Rudimentary Plan for Adaptive Chess'
file_name = 'third-post'
description = 'The third article authored by me'
tags = ['']
posted = '16/11/2023'
estimated_reading_time = 2
author = 'Mijan' 
order = 3